from datetime import datetime
from typing import Dict, List, Optional, Any
from sqlalchemy import Column, Integer, Float, String, DateTime, Text, Boolean, ForeignKey, Index, JSON
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()

class Plant(Base):
    """Plant configuration and metadata."""
    __tablename__ = "plants"
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    location = Column(String)
    operator = Column(String)
    commissioned = Column(DateTime)
    V_liq = Column(Float)
    V_gas = Column(Float)
    T_ad = Column(Float)
    P_el_nom = Column(Float)
    configuration = Column(JSON)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    measurements = relationship("Measurement", back_populates="plant", cascade="all, delete-orphan")
    simulations = relationship("Simulation", back_populates="plant", cascade="all, delete-orphan")
    calibrations = relationship("Calibration", back_populates="plant", cascade="all, delete-orphan")

class Measurement(Base):
    """Time series measurement data."""
    __tablename__ = "measurements"
    id = Column(Integer, primary_key=True)
    plant_id = Column(String, ForeignKey("plants.id"), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    source = Column(String)
    Q_sub_maize = Column(Float)
    Q_sub_manure = Column(Float)
    Q_sub_grass = Column(Float)
    Q_sub_other = Column(Float)
    pH = Column(Float)
    VFA = Column(Float)
    TAC = Column(Float)
    FOS_TAC = Column(Float)
    T_digester = Column(Float)
    Q_gas = Column(Float)
    Q_ch4 = Column(Float)
    Q_co2 = Column(Float)
    CH4_content = Column(Float)
    P_gas = Column(Float)
    P_el = Column(Float)
    P_th = Column(Float)
    is_validated = Column(Boolean, default=False)
    quality_flag = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    plant = relationship("Plant", back_populates="measurements")
    __table_args__ = (Index("idx_plant_timestamp", "plant_id", "timestamp"),)

class Simulation(Base):
    """Simulation run metadata and summary results."""
    __tablename__ = "simulations"
    id = Column(String, primary_key=True)
    plant_id = Column(String, ForeignKey("plants.id"), nullable=False)
    name = Column(String)
    description = Column(Text)
    duration = Column(Float)
    dt = Column(Float)
    scenario = Column(String)
    parameters = Column(JSON)
    initial_state = Column(JSON)
    avg_Q_gas = Column(Float)
    avg_Q_ch4 = Column(Float)
    avg_CH4_content = Column(Float)
    avg_pH = Column(Float)
    avg_VFA = Column(Float)
    total_energy = Column(Float)
    status = Column(String)
    error_message = Column(Text)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)
    plant = relationship("Plant", back_populates="simulations")
    time_series = relationship("SimulationTimeSeries", back_populates="simulation", cascade="all, delete-orphan")

class SimulationTimeSeries(Base):
    """Time series data from simulation."""
    __tablename__ = "simulation_time_series"
    id = Column(Integer, primary_key=True)
    simulation_id = Column(String, ForeignKey("simulations.id"), nullable=False)
    time = Column(Float, nullable=False)
    Q_gas = Column(Float)
    Q_ch4 = Column(Float)
    Q_co2 = Column(Float)
    CH4_content = Column(Float)
    pH = Column(Float)
    VFA = Column(Float)
    TAC = Column(Float)
    FOS_TAC = Column(Float)
    P_el = Column(Float)
    P_th = Column(Float)
    simulation = relationship("Simulation", back_populates="time_series")
    __table_args__ = (Index("idx_simulation_time", "simulation_id", "time"),)

class Calibration(Base):
    """Calibration history and results."""
    __tablename__ = "calibrations"
    id = Column(Integer, primary_key=True)
    plant_id = Column(String, ForeignKey("plants.id"), nullable=False)
    calibration_type = Column(String)
    method = Column(String)
    parameters = Column(JSON)
    parameter_bounds = Column(JSON)
    objectives = Column(JSON)
    objective_weights = Column(JSON)
    objective_value = Column(Float)
    validation_metrics = Column(JSON)
    data_start = Column(DateTime)
    data_end = Column(DateTime)
    n_measurements = Column(Integer)
    success = Column(Boolean)
    message = Column(Text)
    n_iterations = Column(Integer)
    execution_time = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)
    plant = relationship("Plant", back_populates="calibrations")

class Substrate(Base):
    """Substrate characterization data."""
    __tablename__ = "substrates"
    id = Column(Integer, primary_key=True)
    plant_id = Column(String, ForeignKey("plants.id"), nullable=False)
    substrate_name = Column(String, nullable=False)
    substrate_type = Column(String)
    sample_date = Column(DateTime, nullable=False)
    sample_id = Column(String)
    TS = Column(Float)
    VS = Column(Float)
    oTS = Column(Float)
    foTS = Column(Float)
    RP = Column(Float)
    RL = Column(Float)
    RF = Column(Float)
    RA = Column(Float)
    NfE = Column(Float)
    NDF = Column(Float)
    ADF = Column(Float)
    ADL = Column(Float)
    pH = Column(Float)
    NH4_N = Column(Float)
    TAC = Column(Float)
    COD_S = Column(Float)
    BMP = Column(Float)
    BMP_unit = Column(String, default="L_CH4/kg_oTS")
    C_content = Column(Float)
    N_content = Column(Float)
    C_to_N = Column(Float)
    TKN = Column(Float)
    f_ch_xc = Column(Float)
    f_pr_xc = Column(Float)
    f_li_xc = Column(Float)
    k_dis = Column(Float)
    k_hyd_ch = Column(Float)
    k_hyd_pr = Column(Float)
    k_hyd_li = Column(Float)
    lab_name = Column(String)
    analysis_method = Column(String)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    __table_args__ = (Index("idx_plant_substrate_date", "plant_id", "substrate_name", "sample_date"),)
